### ISSUE TITLE
Download takes a very long time

### ISSUE THREAD

**Issue by GuillaumeTong** [ndaidong/vgg-faces-utils#1]
Thank you for providing this script! But the download is taking a very long time.
I have left this script run for 3 or 4 weeks already now, and it seems I am only about half way through the dataset.
Have you considered making the downloads run in parallel using async/multi-threading/multiprocessing? Since there are so many different sources for the images, I think we don't need to consider the case of being banned from websites for trying to query too many things.

**Comment by GuillaumeTong** [comment]
Update: I was able to finish downloading >700 000 remaining images (final count of 1 432 382) in 1 day by refactoring the code into launching the process in 500 threads. The logging became quite messed up, but I could probably fix up my code and make a pull request or something. Would you like that?

**Comment by ndaidong** [comment]
@GuillaumeTong sorry, I've missed your comment for a long time not using this script. There was a [PR](https://github.com/ndaidong/vgg-faces-utils/pull/2) by @ma7555 might resolve your issue.
